Lecture 1: Basic Knowledge of PyTorch

Zhang Huaizheng
huaizhen001@e.ntu.edu.sg
http://zhanghuaizheng.info/PyTorch4DL

Comparison: Numpy and PyTorch

In [2]:
import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([[2, 2, 2],
              [2, 2, 2]])
z = np.array([[3, 3, 3],
              [3, 3, 3]])

a = x * y
b = a + z
c = np.sum(b)

grad_c = 1.0
grad_b = grad_c * np.ones(b.shape)
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a * y
grad_y = grad_a * x

print grad_x
print grad_y

[[ 2.  2.  2.]
 [ 2.  2.  2.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [1]:
import torch
from torch.autograd import Variable

ROW, COL = 2, 3

x = Variable(torch.Tensor([[1, 2, 3],
                           [4, 5, 6]]), requires_grad=True)
y = Variable(torch.Tensor([[2, 2, 2],
                           [2, 2, 2]]), requires_grad=True)
z = Variable(torch.Tensor([[3, 3, 3],
                           [3, 3, 3]]), requires_grad=True)

a = x * y
b = a + z
c = torch.sum(b)

c.backward()
print x.grad.data
print y.grad.data


 2  2  2
 2  2  2
[torch.FloatTensor of size 2x3]


 1  2  3
 4  5  6
[torch.FloatTensor of size 2x3]



Comparison: Tensorflow and PyTorch